apiVersion: apps/v1
kind: Deployment
metadata:
  name: banrep-price-capture-prod
  labels:
    app: banrep-price-capture
    environment: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banrep-price-capture
      environment: prod
  template:
    metadata:
      labels:
        app: banrep-price-capture
        environment: prod
    spec:
      containers:
        - name: banrep-price-capture
          image: banrep-price-capture:prod
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: BANREP_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: banrep-price-capture-secrets-prod
                  key: db-host
            - name: BANREP_DB_HOST_RO
              valueFrom:
                secretKeyRef:
                  name: banrep-price-capture-secrets-prod
                  key: db-host-ro
            - name: BANREP_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: banrep-price-capture-secrets-prod
                  key: db-username
            - name: BANREP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banrep-price-capture-secrets-prod
                  key: db-password
            - name: BANREP_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: banrep-price-capture-secrets-prod
                  key: bearer-token
            - name: BANREP_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: banrep-price-capture-secrets-prod
                  key: rabbitmq-username
            - name: BANREP_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banrep-price-capture-secrets-prod
                  key: rabbitmq-password
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: banrep-price-capture-prod
  labels:
    app: banrep-price-capture
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: banrep-price-capture
    environment: prod
  ports:
    - name: http
      port: 80
      targetPort: http
